baseURL: "https://safffrron.github.io/"
languageCode: "en-us"
title: "Kislay"
theme: "PaperMod"

markup:
  goldmark:
    renderer:
      unsafe: true

outputs:
  home:
    - HTML
    - RSS
    - JSON

# Enable features like search and dark mode
params:
  ShowBreadCrumbs: true
  assets:
    css: ["css/custom.css"]

  search:
    enabled: true
    # location: navbar
    fuse:
      isCaseSensitive: false
      minMatchCharLength: 2
      threshold: 0.3
  assets:
    disableHLJS: false
  menu:
    main:
      showDropdownOnHover: true

  defaultTheme: light # auto | dark | light
  showReadingTime: true
  showtoc: false
  ShowPostNavLinks: false
  ShowShareButtons: false
  ShowCodeCopyButtons: true
  ShowSearch: true

  ShowPostsOnHomePage: false


menu:
  main:
    - identifier: search
      name: Search
      url: /search/
      weight: 5

    - identifier: home
      name: Home
      url: /
      weight: 1

    - identifier: academics
      name: Academics
      url: /academics/
      weight: 2

    - parent: academics
      name: CV
      url: /academics/cv/
      weight: 1

    - parent: academics
      name: Projects
      url: /academics/projects/
      weight: 2

    - parent: academics
      name: Courses Taken
      url: /academics/courses/
      weight: 3

    - parent: academics
      name: Publications
      url: /academics/publications/
      weight: 4

    - identifier: hobbies
      name: Hobbies
      url: /hobbies/
      weight: 3

    - parent: hobbies
      name: Book Reviews / Blogs
      url: /hobbies/books/
      weight: 1

    - parent: hobbies
      name: Quotes
      url: /hobbies/quotes/
      weight: 2

    - parent: hobbies
      name: Anime Tier List
      url: /hobbies/anime/
      weight: 3

    - identifier: contact
      name: Contact Me
      url: /contact/
      weight: 4

    - identifier: search
      name: Search
      url: /search/
      weight: 5




